CREATE TABLE [dbo].[PNPU_H_REPORT] (
    [ITERATION]     NUMERIC (18) NULL,
    [WORKFLOW_ID]   NUMERIC (18) NULL,
    [ID_PROCESS]    NUMERIC (18) NULL,
    [CLIENT_ID]     VARCHAR (50) NULL,
    [JSON_TEMPLATE] TEXT         NULL
);

