CREATE TABLE [dbo].[PNPU_STEP] (
    [ORDER_ID]    NUMERIC (18) NOT NULL,
    [ID_PROCESS]  NUMERIC (18) NOT NULL,
    [WORKFLOW_ID] NUMERIC (18) NOT NULL,
    CONSTRAINT [PK_PNPU_STEP] PRIMARY KEY CLUSTERED ([ORDER_ID] ASC),
    CONSTRAINT [FK_PNPU_STEP_PNPU_PROCESS] FOREIGN KEY ([ID_PROCESS]) REFERENCES [dbo].[PNPU_PROCESS] ([ID_PROCESS]),
    CONSTRAINT [FK_PNPU_STEP_PNPU_WORKFLOW] FOREIGN KEY ([WORKFLOW_ID]) REFERENCES [dbo].[PNPU_WORKFLOW] ([WORKFLOW_ID]),
    CONSTRAINT [IX_PNPU_STEP] UNIQUE NONCLUSTERED ([ORDER_ID] ASC)
);

