CREATE TABLE [dbo].[PNPU_DEP_REF] (
    [ID_H_WORKFLOW]         NUMERIC (18) NULL,
    [NIV_DEP]               NCHAR (10)   NULL,
    [CCT_TASK_ID]           VARCHAR (50) NULL,
    [CCT_OBJECT_TYPE]       VARCHAR (50) NULL,
    [CCT_PARENT_OBJ_ID]     VARCHAR (50) NULL,
    [DEP_CCT_TASK_ID]       VARCHAR (50) NULL,
    [DEP_CCT_OBJECT_TYPE]   VARCHAR (50) NULL,
    [DEP_CCT_OBJECT_ID]     VARCHAR (50) NULL,
    [DEP_CCT_PARENT_OBJ_ID] VARCHAR (50) NULL,
    [DEP_CCT_ACTION_TYPE]   VARCHAR (50) NULL,
    [DEP_CCT_PACK_TYPE]     VARCHAR (50) NULL,
    [DEP_CCT_COMMAND_TYPE]  NUMERIC (18) NULL
);

