CREATE TABLE [dbo].[PNPU_H_STEP] (
    [ITERATION]      NUMERIC (18) NULL,
    [ID_H_STEP]      NUMERIC (18) NOT NULL,
    [WORKFLOW_ID]    NUMERIC (18) NULL,
    [ID_PROCESS]     NUMERIC (18) NULL,
    [CLIENT_ID]      VARCHAR (50) NULL,
    [USER_ID]        VARCHAR (50) NULL,
    [LAUNCHING_DATE] DATETIME     NULL,
    [ENDING_DATE]    DATETIME     NULL,
    [ID_STATUT]      VARCHAR (50) NULL,
    [TYPOLOGY]       VARCHAR (50) NULL,
    CONSTRAINT [PK_PNPU_H_STEP] PRIMARY KEY CLUSTERED ([ID_H_STEP] ASC)
);

